

openapi: 3.0.0
info:
  title: Assessment
  description: |
    Participants will build a Personal Habit Tracker application
    - **POST /register**: Register a new user.
    - **POST /login**: Authenticate and return a JWT token.
    - **GET /habits**: Fetch all habits for the authenticated user.
    - **POST /habits**: Create a new habit.
    - **PUT /habits/{id}**: Update an existing habit.
    - **DELETE /habits/{id}**: Delete a habit.
    - **GET /progress**: Fetch progress for all habits (e.g., streak counts, completion percentage).
servers:
  - url: http://localhost:9000
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: Authorization
      in: header

tags:
  - name: Users
    description: User management endpoints
  - name: Habits
    description: Habit management endpoints
paths:
  /auth/register:
    post:
      tags:
        - Users
      summary: Register a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input
  /auth/login:
    post:
      tags:
        - Users
      summary: Authenticate and return a JWT token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Authentication successful, JWT token returned
        '401':
          description: Authentication failed
  /api/habit:
    get:
      tags:
        - Habits
      summary: Fetch all habits for the authenticated user
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: List of habits
        '401':
          description: Unauthorized
    post:
      tags:
        - Habits
      summary: Create a new habit
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
              required:
                - title
      responses:
        '201':
          description: Habit created successfully
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
  /habit/{id}:
    put:
      tags:
        - Habits
      summary: Update an existing habit
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Habit updated successfully
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Habit not found
    delete:
      tags:
        - Habits
      summary: Delete a habit
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Habit deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Habit not found
  /progress:
    get:
      tags:
        - Habits
      summary: Fetch progress for all habits (e.g., streak counts, completion percentage)
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Habit progress data
        '401':
          description: Unauthorized
  /progress/{id}:
    get:
      tags:
        - Habits
      summary: Fetch progress for all habits (e.g., streak counts, completion percentage)
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Habit progress data
        '401':
          description: Unauthorized
