name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install  # or your preferred package manager

      - name: Build the project
        run: npm start  # Change this to your build command

      # - name: Deploy
      #   run: |
      #     echo "Deploying to the server..."
      #     # Add your deployment commands here
